### ISSUE TITLE
[BUG] 无法启动koishi！

### ISSUE THREAD

**Issue by zhishifenzi8266** [koishijs/koishi-android#15]
**
安卓系统：8.1
手机：三星 SM-G531H
系统：LineageOS 15.1
CPU: 32位处理器
**
![_422199727489b22b3cae61dd9826d1f9_367510024_IMG_20240430_012727](https://github.com/koishijs/koishi-android/assets/168508626/66e791cc-c297-498f-a442-9eebffe35de4)

**Comment by Anillc** [comment]
这个仓库暂时没有时间维护。不过 32 位 arm 应该是未来也不会支持，建议找一台 aarch64 的设备来运行 koishi-android

**Comment by zhishifenzi8266** [comment]
好的👌谢谢！
